const VERSION='v1.1',MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const ART=[
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Morris_Strawberry_Thief_1883.jpg/1280px-Morris_Strawberry_Thief_1883.jpg',title:'Strawberry Thief',artist:'William Morris',date:'1883'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/1280px-Tsunami_by_hokusai_19th_century.jpg',title:'The Great Wave',artist:'Katsushika Hokusai',date:'c. 1831'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Amandelbloesem_-_s0176V1962_-_Van_Gogh_Museum.jpg/1280px-Amandelbloesem_-_s0176V1962_-_Van_Gogh_Museum.jpg',title:'Almond Blossom',artist:'Vincent van Gogh',date:'1890'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Odilon_Redon_-_Butterflies_-_Google_Art_Project.jpg/1280px-Odilon_Redon_-_Butterflies_-_Google_Art_Project.jpg',title:'Butterflies',artist:'Odilon Redon',date:'c. 1910'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Willow_Bough_MET_DP306734.jpg/1280px-Willow_Bough_MET_DP306734.jpg',title:'Willow Bough',artist:'William Morris',date:'1887'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/1280px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg',title:'Water Lilies',artist:'Claude Monet',date:'1906'},
 {url:'https://upload.wikimedia.org/wikipedia/commons/e/ea/Klimt_-_Bl%C3%BChende_Wiese.jpg',title:'Flowering Meadow',artist:'Gustav Klimt',date:'1906'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/%E8%91%9B%E9%A3%BE%E5%8C%97%E6%96%8E%E7%94%BB_%E7%87%95%E5%AD%90%E8%8A%B1-Grasshopper_and_Iris_MET_DP141267.jpg/1280px-%E8%91%9B%E9%A3%BE%E5%8C%97%E6%96%8E%E7%94%BB_%E7%87%95%E5%AD%90%E8%8A%B1-Grasshopper_and_Iris_MET_DP141267.jpg',title:'Grasshopper and Iris',artist:'Katsushika Hokusai',date:'1830s'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Willow_Bough_MET_DP306734.jpg/1280px-Willow_Bough_MET_DP306734.jpg',title:'Willow Bough',artist:'William Morris',date:'1887'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/De_pruimenboomgaard_te_Kameido-Rijksmuseum_RP-P-1956-743.jpeg/1280px-De_pruimenboomgaard_te_Kameido-Rijksmuseum_RP-P-1956-743.jpeg',title:'Plum Garden at Kameido',artist:'Utagawa Hiroshige',date:'1857'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Odilon_Redon_-_Butterflies_-_Google_Art_Project.jpg/1280px-Odilon_Redon_-_Butterflies_-_Google_Art_Project.jpg',title:'Butterflies',artist:'Odilon Redon',date:'c. 1910'},
 {url:'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/1280px-Tsunami_by_hokusai_19th_century.jpg',title:'The Great Wave',artist:'Katsushika Hokusai',date:'c. 1831'}
];
const ART_INFO={
 'Strawberry Thief':{zh:'《草莓小偷》',style:'英国工艺美术运动 · 植物纹样设计',text:'威廉·莫里斯以画眉、草莓与繁密叶片构成重复纹样。作品把日常织物变成可生活其中的艺术，也是工艺美术运动“艺术回到日常”的代表。',artistUrl:'https://zh.wikipedia.org/wiki/%E5%A8%81%E5%BB%89%C2%B7%E8%8E%AB%E9%87%8C%E6%96%AF'},
 'The Great Wave':{zh:'《神奈川冲浪里》',style:'日本浮世绘 · 木版画',text:'葛饰北斋用巨浪、远处富士山与舟上人物制造强烈尺度对比。弧形浪爪与平面色块影响了后来的欧洲印象派与现代设计。',artistUrl:'https://zh.wikipedia.org/wiki/%E8%91%9B%E9%A5%B0%E5%8C%97%E6%96%8B'},
 'Almond Blossom':{zh:'《盛开的杏花》',style:'后印象派 · 油画',text:'梵高以清亮蓝色背景衬托杏树枝条，借鉴日本浮世绘的裁切和轮廓。它是一幅庆祝新生命的作品，气质明净而安静。',artistUrl:'https://zh.wikipedia.org/wiki/%E6%96%87%E6%A3%AE%E7%89%B9%C2%B7%E6%A2%B5%E9%AB%98'},
 'Butterflies':{zh:'《蝴蝶》',style:'象征主义 · 粉彩与油画',text:'奥迪隆·雷东把现实中的花与蝶处理成梦境般的色彩空间。轻盈形态与朦胧背景体现了象征主义重视内在感受和想象的倾向。',artistUrl:'https://zh.wikipedia.org/wiki/%E5%A5%A7%E8%BF%AA%E9%9A%86%C2%B7%E9%9B%B7%E4%B8%B9'},
 'Willow Bough':{zh:'《柳枝》',style:'英国工艺美术运动 · 壁纸纹样',text:'莫里斯从河畔柳树得到灵感，让弯曲枝条和细叶在画面中自然循环。克制的植物色与连续节奏，使装饰兼具秩序和生命力。',artistUrl:'https://zh.wikipedia.org/wiki/%E5%A8%81%E5%BB%89%C2%B7%E8%8E%AB%E9%87%8C%E6%96%AF'},
 'Water Lilies':{zh:'《睡莲》',style:'印象派 · 油画',text:'莫奈反复观察吉维尼花园的水面、光线与倒影。画中弱化地平线，让色彩和笔触成为主体，呈现时间流动中的瞬间感受。',artistUrl:'https://zh.wikipedia.org/wiki/%E5%85%8B%E5%8A%B3%E5%BE%B7%C2%B7%E8%8E%AB%E5%A5%88'},
 'Flowering Meadow':{zh:'《繁花草地》',style:'维也纳分离派 · 风景画',text:'克里姆特将自然景色组织成近乎织物般的色点与花纹。画面没有明显叙事，观者会先感受到色彩密度、节奏和装饰性的平面结构。',artistUrl:'https://zh.wikipedia.org/wiki/%E5%8F%A4%E6%96%AF%E5%A1%94%E5%A4%AB%C2%B7%E5%85%8B%E9%87%8C%E5%A7%86%E7%89%B9'},
 'Grasshopper and Iris':{zh:'《鸢尾与蚱蜢》',style:'日本浮世绘 · 花鸟画',text:'葛饰北斋以简洁线条捕捉鸢尾叶片的方向和昆虫的瞬间姿态。大片留白与不对称构图让微小自然生命显得格外清晰。',artistUrl:'https://zh.wikipedia.org/wiki/%E8%91%9B%E9%A5%B0%E5%8C%97%E6%96%8B'},
 'Plum Garden at Kameido':{zh:'《龟户梅屋铺》',style:'日本浮世绘 · 名所绘',text:'歌川广重用近景粗大的梅枝切开画面，远处游人与花园被压缩在其后。这种大胆取景后来影响了梵高等欧洲艺术家。',artistUrl:'https://zh.wikipedia.org/wiki/%E6%AD%8C%E5%B7%9D%E5%BB%A3%E9%87%8D'}
};
const CHINA_OFF_2026=new Set(['01-01','01-02','01-03','02-15','02-16','02-17','02-18','02-19','02-20','02-21','02-22','02-23','04-04','04-05','04-06','05-01','05-02','05-03','05-04','05-05','06-19','06-20','06-21','09-25','09-26','09-27','10-01','10-02','10-03','10-04','10-05','10-06','10-07']);
const CHINA_WORK_2026=new Set(['01-04','02-14','02-28','05-09','09-20','10-10']);
const FESTIVALS={'01-01':'元旦','02-14':'情人节','03-08':'妇女节','03-12':'植树节','04-22':'世界地球日','05-01':'劳动节','05-04':'青年节','06-01':'儿童节','06-05':'世界环境日','07-01':'建党节','08-01':'建军节','09-10':'教师节','10-01':'国庆节','10-31':'万圣夜','12-24':'平安夜','12-25':'圣诞节'},FESTIVALS_2026={'2026-03-20':'春分','2026-04-05':'清明','2026-05-10':'母亲节','2026-06-19':'端午节','2026-06-21':'父亲节','2026-09-22':'秋分','2026-09-25':'中秋节','2026-11-26':'感恩节','2026-12-22':'冬至'},WORLD=new Set(['02-14','03-08','04-22','05-10','06-05','06-21','10-31','11-26','12-24','12-25']);
const initialRoster={year:2026,month:9,owner:'陈可',people:[{name:'骆蒋婷',location:'六小龙展厅',rest:[5,6,13,14,20,21,26,27,28]},{name:'孙思怡',location:'六小龙展厅',rest:[4,5,11,12,18,19,24,25,30]},{name:'潘柳杉',location:'数贸港（2楼）',rest:[4,5,11,12,19,20,21,22,23]},{name:'林雨柔',location:'数贸港（2楼）暂时',rest:[6,7,13,14,20,28,29,30]},{name:'陈可',location:'数贸港（1楼+2楼）',rest:[4,5,9,10,17,24,25,26]},{name:'朱紫珂',location:'数贸港（1楼）',rest:[6,7,13,14,20,27,28,29]},{name:'郭仕仕',location:'二区东A展厅',rest:[5,6,12,13,19,25,26,27]},{name:'朱晓璐',location:'中福（暂时）',rest:[5,6,12,13,19,28,29,30]}]};
let roster=JSON.parse(localStorage.getItem('slm-roster')||'null')||initialRoster,notes=JSON.parse(localStorage.getItem('slm-notes')||'{}'),settings=JSON.parse(localStorage.getItem('slm-settings')||'{"world":true,"lunar":true}'),cursor=new Date();cursor.setDate(1);let selectedDate='',teamSelected='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],pad=n=>String(n).padStart(2,'0'),daysIn=(y,m)=>new Date(y,m,0).getDate(),keyFor=(y,m,d)=>`${y}-${pad(m)}-${pad(d)}`;
function officialType(y,m,d){if(y!==2026)return'';const md=`${pad(m)}-${pad(d)}`;return CHINA_WORK_2026.has(md)?'work':CHINA_OFF_2026.has(md)?'rest':''}function requiredRest(y,m){let n=0;for(let d=1;d<=daysIn(y,m);d++){const t=officialType(y,m,d),w=new Date(y,m-1,d).getDay();if(t==='rest'||(!t&&(!w||w===6)))n++}return n}function ownerRow(y,m){return y===roster.year&&m===roster.month?roster.people.find(p=>p.name===roster.owner):null}function lunar(date){try{return new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{day:'numeric'}).formatToParts(date).find(p=>p.type==='day')?.value||''}catch{return''}}function festival(y,m,d){const md=`${pad(m)}-${pad(d)}`,full=`${y}-${md}`;if(WORLD.has(md)&&!settings.world)return'';return FESTIVALS_2026[full]||FESTIVALS[md]||''}function status(y,m,d){const o=notes[keyFor(y,m,d)]?.status;if(o&&o!=='unset')return o;const row=ownerRow(y,m);if(row)return row.rest.includes(d)?'rest':'work';return officialType(y,m,d)||'unset'}
function setAccent(img){try{const c=document.createElement('canvas'),x=c.getContext('2d');c.width=c.height=24;x.drawImage(img,0,0,24,24);const data=x.getImageData(0,0,24,24).data;let r=0,g=0,b=0,n=0;for(let i=0;i<data.length;i+=16){if(data[i+3]>100){r+=data[i];g+=data[i+1];b+=data[i+2];n++}}r=Math.round(r/n*.72);g=Math.round(g/n*.72);b=Math.round(b/n*.72);document.documentElement.style.setProperty('--accent',`rgb(${r},${g},${b})`);document.documentElement.style.setProperty('--accent-rgb',`${r},${g},${b}`)}catch{}}
function renderArt(y,m){const w=ART[m-1],card=$('#artwork'),img=$('#monthArt');card.classList.add('loading');$('#artTitle').textContent=w.title;$('#artNote').textContent=`${w.artist} · ${w.date}`;img.onload=()=>{card.classList.remove('loading');setAccent(img)};img.onerror=()=>{$('#artNote').textContent='馆藏图片暂时无法载入'};img.src=w.url}
function commonsPage(url){const p=new URL(url).pathname.split('/').filter(Boolean),i=p.indexOf('thumb'),name=i>=0?p[p.length-2]:p[p.length-1];return `https://commons.wikimedia.org/wiki/File:${name}`}function openArt(){const w=ART[cursor.getMonth()],info=ART_INFO[w.title];$('#artDetailTitle').textContent=info?.zh||w.title;$('#artDetailByline').textContent=`${w.artist} · ${w.date}｜${info?.style||'艺术作品'}`;$('#artDetailText').textContent=info?.text||'点击下方链接浏览作品与艺术家资料。';$('#artArtistLink').href=info?.artistUrl||'https://zh.wikipedia.org/';$('#artSourceLink').href=commonsPage(w.url);$('#artDialog').showModal()}
function makeDay(y,m,d,mode){const date=new Date(y,m-1,d),key=keyFor(y,m,d),s=status(y,m,d),official=officialType(y,m,d),f=festival(y,m,d),rec=notes[key],btn=document.createElement('button');btn.className=`day ${s==='work'?'work-day':s==='rest'?'rest-day':''} ${official==='rest'?'official-rest':official==='work'?'official-work':''} ${rec&&(rec.title||rec.note)?'has-record':''} ${teamSelected===key?'selected':''}`;const officialLabel=official==='work'?'补班':official==='rest'?(f||'法定休'):'',minor=mode==='team'?(officialLabel||f||''):(rec?.title||officialLabel||f||(settings.lunar?lunar(date):''));btn.innerHTML=`<span class="num">${d}</span><span class="minor">${minor||'&nbsp;'}</span>${mode==='mine'&&s!=='unset'?`<span class="status">${s==='work'?'班':'休'}</span>`:''}`;btn.onclick=()=>mode==='mine'?openDay(key):showDuty(key);return btn}
function fillCalendar(el,y,m,mode){el.innerHTML='';const first=(new Date(y,m-1,1).getDay()+6)%7;for(let i=0;i<first;i++)el.insertAdjacentHTML('beforeend','<span class="day empty"></span>');for(let d=1;d<=daysIn(y,m);d++)el.append(makeDay(y,m,d,mode))}
function render(){const y=cursor.getFullYear(),m=cursor.getMonth()+1,row=ownerRow(y,m),rest=row?.rest.length||0,work=row?daysIn(y,m)-rest:0;$('#monthEn').textContent=MONTHS[m-1];$('#monthNum').textContent=`/${pad(m)}`;$('#yearText').textContent=y;$('#teamMonth').textContent=`${y}/${pad(m)}`;renderArt(y,m);fillCalendar($('#calendarGrid'),y,m,'mine');fillCalendar($('#teamCalendar'),y,m,'team');$('#summaryStrip').innerHTML=summary([['上班',work],['实休',rest],['应休',requiredRest(y,m)]]);$('#recordSummary').innerHTML=summary([['已记录',Object.keys(notes).filter(k=>k.startsWith(`${y}-${pad(m)}`)).length],['上班',work],['休息',rest]])}
function summary(a){return a.map(([l,v])=>`<div class="summary-item"><strong>${v}</strong><span>${l}</span></div>`).join('')}
function showDuty(key){teamSelected=key;const [y,m,d]=key.split('-').map(Number),same=y===roster.year&&m===roster.month,on=same?roster.people.filter(p=>!p.rest.includes(d)):[],off=same?roster.people.filter(p=>p.rest.includes(d)):[];$('#dutyDate').textContent=`${m}月${d}日 · 在岗 ${on.length} 人 · 休息 ${off.length} 人`;$('#dutyList').innerHTML=on.length?on.map(p=>`<span class="duty-person">${p.name}<small>${p.location}</small></span>`).join(''):'<span class="quiet">这个月份还没有导入团队排班</span>';fillCalendar($('#teamCalendar'),y,m,'team')}
function openDay(key){selectedDate=key;const [y,m,d]=key.split('-').map(Number),n=notes[key]||{},s=status(y,m,d);$('#dialogDate').textContent=`${y} / ${pad(m)} / ${pad(d)}`;$('#dialogTitle').textContent=festival(y,m,d)||`星期${'日一二三四五六'[new Date(y,m-1,d).getDay()]}`;$('#eventTitle').value=n.title||'';$('#eventNote').value=n.note||'';($(`input[name="status"][value="${n.status||s}"]`)||$('input[value="unset"]')).checked=true;$('#dayDialog').showModal()}
function saveDay(){notes[selectedDate]={status:$('input[name="status"]:checked').value,title:$('#eventTitle').value.trim(),note:$('#eventNote').value.trim()};localStorage.setItem('slm-notes',JSON.stringify(notes));render();toast('已保存')}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1500)}
function validate(d){if(!d||!Number.isInteger(d.year)||!Number.isInteger(d.month)||!Array.isArray(d.people))throw Error('排班格式不正确');return d}function importFile(file){const r=new FileReader();r.onload=()=>{try{roster=validate(JSON.parse(r.result));localStorage.setItem('slm-roster',JSON.stringify(roster));cursor=new Date(roster.year,roster.month-1,1);render();toast('导入成功')}catch(e){$('#importStatus').textContent=e.message}};r.readAsText(file)}function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({...roster,notes},null,2)],{type:'application/json'}));a.download=`上班了没-${roster.year}-${pad(roster.month)}.json`;a.click()}
function shift(n){cursor.setMonth(cursor.getMonth()+n);teamSelected='';render()}$('#prevMonth').onclick=()=>shift(-1);$('#nextMonth').onclick=()=>shift(1);$('#teamPrev').onclick=()=>shift(-1);$('#teamNext').onclick=()=>shift(1);['prevMonth','nextMonth','teamPrev','teamNext'].forEach(id=>{$('#'+id).addEventListener('dblclick',e=>e.preventDefault())});$('#artwork').onclick=openArt;$('#artwork').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openArt()}};$('.art-close').onclick=()=>$('#artDialog').close();$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.view,.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')});$('#saveDay').onclick=e=>{e.preventDefault();saveDay();$('#dayDialog').close()};$('#deleteRecord').onclick=()=>{delete notes[selectedDate];localStorage.setItem('slm-notes',JSON.stringify(notes));render();$('#dayDialog').close()};$('#importFile').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);$('#exportBtn').onclick=exportData;$('#worldToggle').checked=settings.world;$('#lunarToggle').checked=settings.lunar;$('#worldToggle').onchange=e=>{settings.world=e.target.checked;localStorage.setItem('slm-settings',JSON.stringify(settings));render()};$('#lunarToggle').onchange=e=>{settings.lunar=e.target.checked;localStorage.setItem('slm-settings',JSON.stringify(settings));render()};render();
